name = "QuantumGeometricComplexity"
uuid = "123e4567-e89b-12d3-a456-426614174000"  
authors = ["Your Name <youremail@example.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
